#!/usr/bin/env python3
"""
gen_checklists_bundle.py  (S160)
────────────────────────────────
Bundles the 14 domains' checklist.json + clauses.json into a single
repo-root `checklists_bundle.json` that the backend `/api/checklist-revise`
endpoint loads at runtime (mirrors how role_facts.json is loaded — root file,
resolved via ../../../ from the compiled api module, present on Render).

Per domain we keep only what the endpoint needs:
  sections[].items[]   : req, quote, page, source_id, school_types  (the requirements to score coverage against)
  clauses[]            : si, covers, school_types, text, table       (the model clauses to supplement missing items)
  src                  : source_id -> [title, url]                   (citations)

Re-run after any checklist/clauses change:
  cd ".../Draft" && python3 dev/checklists/_work/gen_checklists_bundle.py
(--check prints summary without writing)
"""
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]            # …/Draft
WORK = REPO_ROOT / "dev" / "checklists" / "_work"
OUT = REPO_ROOT / "checklists_bundle.json"
PROFILES = REPO_ROOT / "dev" / "checklists" / "_school_type_profiles.json"
ALL_TYPES = {"kindergarten", "primary", "secondary", "special"}


def domain_school_types():
    """Map domain key -> list of applicable school types from the profiles.
    Omit (None) when a domain applies to all 4 types (= 'applies to all', backward-compatible).
    Used as the domain-level fallback for untagged clauses/items (S162 ①: untagged clause
    in a type-scoped domain like kg_operation must NOT leak to other school types)."""
    if not PROFILES.exists():
        return {}
    out = {}
    for p in json.loads(PROFILES.read_text(encoding="utf-8")):
        ap = p.get("applies_to", {})
        on = sorted(k for k, v in ap.items() if v)
        if on and set(on) != ALL_TYPES:        # all-4 -> omit (means "all")
            out[p["domain"]] = on
    return out

DOMAIN_ORDER = [
    "safety", "conduct", "curriculum", "sen", "student_support", "gifted",
    "cpd", "hr_admin", "activity", "placement", "qa_inspection",
    "gov_admin", "school_governance", "kg_admission", "kg_operation",
]


def trim_item(it: dict) -> dict:
    # req is the normalized requirement text — the embedding signal + display label.
    # quote (raw source excerpt) intentionally dropped: ~halves bundle size, req scores better.
    o = {"req": it.get("req", "")}
    if it.get("page") is not None:
        o["page"] = it["page"]
    if it.get("source_id"):
        o["source_id"] = it["source_id"]
    st = it.get("school_types")
    if st:                                   # None / [] both mean "all types" -> omit
        o["school_types"] = st
    return o


def trim_clause(cl: dict) -> dict:
    o = {"text": cl.get("text", "")}
    if cl.get("covers"):
        o["covers"] = cl["covers"]
    st = cl.get("school_types")
    if st:
        o["school_types"] = st
    if cl.get("table"):
        o["table"] = cl["table"]
    return o


def main():
    check_only = "--check" in sys.argv[1:]
    domains = {}
    dom_types = domain_school_types()
    tot_items = tot_clauses = 0
    for key in DOMAIN_ORDER:
        cj = WORK / key / "checklist.json"
        lj = WORK / key / "clauses.json"
        if not cj.exists() or not lj.exists():
            print(f"  ⚠ missing json for {key}", file=sys.stderr)
            continue
        chk = json.loads(cj.read_text(encoding="utf-8"))
        clauses_raw = json.loads(lj.read_text(encoding="utf-8"))
        sections = []
        for sec in chk.get("sections", []):
            items = [trim_item(it) for it in sec.get("items", [])]
            sections.append({"name": sec.get("name", ""), "items": items})
            tot_items += len(items)
        clauses = []
        for ch in clauses_raw:                # list of {si, section_name, clauses[]}
            si = ch.get("si")
            for cl in ch.get("clauses", []):
                tc = trim_clause(cl)
                tc["si"] = si
                clauses.append(tc)
                tot_clauses += 1
        domains[key] = {
            "key": key,
            "cn": chk.get("cn", key),
            "src": chk.get("src", {}),
            "sections": sections,
            "clauses": clauses,
        }
        if key in dom_types:                    # domain-level school-type scope (fallback for untagged)
            domains[key]["school_types"] = dom_types[key]

    bundle = {
        "generated_note": "Auto-generated by dev/checklists/_work/gen_checklists_bundle.py — do not hand-edit; re-run after checklist/clauses change.",
        "domain_count": len(domains),
        "domains": domains,
    }

    print(f"domains={len(domains)}  total_items={tot_items}  total_clauses={tot_clauses}")
    for k, d in domains.items():
        nitems = sum(len(s["items"]) for s in d["sections"])
        print(f"  {k:18} {d['cn']:10} sections={len(d['sections'])} items={nitems} clauses={len(d['clauses'])}")

    if check_only:
        print("(--check: not written)")
        return
    OUT.write_text(json.dumps(bundle, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    kb = OUT.stat().st_size / 1024
    print(f"→ wrote {OUT.relative_to(REPO_ROOT)}  ({kb:.0f} KB)")


if __name__ == "__main__":
    main()
