#!/usr/bin/env python3
"""
gen_templates_manifest.py  (S160)
─────────────────────────────────
Scans the 14 domain folders under dev/checklists/<域>/ for the generated
"學校版" (本校…政策…) and "清單版" (校本…要求清單) .docx deliverables and emits
a flat manifest the app.html「政策範本」tab fetches at runtime.

Output (repo root): policy_templates.json
  {
    "generated_note": "...",
    "total_files": <int>,
    "base_path": "dev/checklists",
    "domains": [
      { "key": "safety", "cn": "學校安全",
        "files": [
          {"kind":"policy"|"checklist", "school_type":""|"primary"|"secondary"|"special",
           "type_label":"通用"|"小學"|"中學"|"特殊學校",
           "name": "<filename.docx>", "path":"dev/checklists/safety/<filename.docx>",
           "size": <bytes>} , ... ]
      }, ...
    ]
  }

Re-run after any docx regeneration:
  cd ".../Draft" && python3 dev/checklists/_work/gen_templates_manifest.py
(use --check to print summary without writing)

Live URL of a file = https://<domain>/<urlencode(path)>  (GitHub Pages, .nojekyll on)
school_type field reuses app.html ANALYZE_SCHOOL_LABELS canonical keys.
"""
import json
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]          # …/Draft  (_work/checklists/dev/Draft)
CHECKLISTS = REPO_ROOT / "dev" / "checklists"
WORK = CHECKLISTS / "_work"
OUT = REPO_ROOT / "policy_templates.json"

# canonical domain order (matches checklist build order; kg_admission last = 幼稚園收生)
DOMAIN_ORDER = [
    "safety", "conduct", "curriculum", "sen", "student_support", "gifted",
    "cpd", "hr_admin", "activity", "placement", "qa_inspection",
    "gov_admin", "school_governance", "kg_admission", "kg_operation",
]

TYPE_SUFFIX = {  # filename token -> (canonical school_type, label)
    "小學": ("primary", "小學"),
    "中學": ("secondary", "中學"),
    "特殊學校": ("special", "特殊學校"),
    "幼稚園": ("kindergarten", "幼稚園"),
}


def domain_cn(key: str) -> str:
    cj = WORK / key / "checklist.json"
    if cj.exists():
        try:
            return json.loads(cj.read_text(encoding="utf-8")).get("cn", key)
        except Exception:
            pass
    return key


def classify(name: str):
    """Return (kind, school_type, type_label) for a docx filename, or None to skip."""
    if not name.endswith(".docx"):
        return None
    # kind
    if name.startswith("本校") and "學校版" in name:
        kind = "policy"
    elif name.startswith("校本") and "要求清單" in name:
        kind = "checklist"
    else:
        return None  # stray / sample docx — not part of the 14-domain set
    # school_type from suffix token (…_小學_DRAFT / …_中學_DRAFT / …_特殊學校_DRAFT)
    school_type, label = "", "通用"
    for token, (st, lbl) in TYPE_SUFFIX.items():
        if f"_{token}_" in name:
            school_type, label = st, lbl
            break
    return kind, school_type, label


# stable sort key: policy before checklist, then 通用/小學/中學/特殊學校/幼稚園
KIND_RANK = {"policy": 0, "checklist": 1}
TYPE_RANK = {"": 0, "primary": 1, "secondary": 2, "special": 3, "kindergarten": 4}


def main():
    check_only = "--check" in sys.argv[1:]
    domains = []
    total = 0
    for key in DOMAIN_ORDER:
        ddir = CHECKLISTS / key
        if not ddir.is_dir():
            print(f"  ⚠ missing domain dir: {key}", file=sys.stderr)
            continue
        files = []
        for name in sorted(os.listdir(ddir)):
            cls = classify(name)
            if not cls:
                continue
            kind, school_type, label = cls
            fp = ddir / name
            files.append({
                "kind": kind,
                "school_type": school_type,
                "type_label": label,
                "name": name,
                "path": f"dev/checklists/{key}/{name}",
                "size": fp.stat().st_size,
            })
        files.sort(key=lambda f: (KIND_RANK[f["kind"]], TYPE_RANK[f["school_type"]]))
        total += len(files)
        domains.append({"key": key, "cn": domain_cn(key), "files": files})

    manifest = {
        "generated_note": "Auto-generated by dev/checklists/_work/gen_templates_manifest.py — do not hand-edit; re-run after docx regeneration.",
        "total_files": total,
        "base_path": "dev/checklists",
        "domains": domains,
    }

    print(f"domains={len(domains)}  total_docx={total}")
    for d in domains:
        pol = sum(1 for f in d["files"] if f["kind"] == "policy")
        chk = sum(1 for f in d["files"] if f["kind"] == "checklist")
        print(f"  {d['key']:18} {d['cn']:10} policy={pol} checklist={chk}")

    if check_only:
        print("(--check: not written)")
        return
    OUT.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"→ wrote {OUT.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
